
version: '3'

services:
  back:
    build: ./calcula-frete-infra
    container_name: calcula-frete
    volumes:
      - ./calcula-frete-infra/projeto/:/workspace
    restart: always
    ports:
      - "8080:8080"
    stdin_open: true   
    command: /bin/bash

